### ISSUE TITLE
Upper case error in requireDaysPriorObservation()

### ISSUE THREAD

**Issue by JTBrash** [darwin-eu/DrugUtilisation#4]
Hi,
I have an 'invalid identifier '"cohort_end_Date"'' error when running generateDrugUtilisationCohortSet().
I think the error occurs when calling requireDaysPriorObservation(), where line 371 should be 'cohort_end_date', not 'cohort_end_Date'.

https://github.com/darwin-eu/DrugUtilisation/blob/4e36895a9d68cc15fffde8ada5f57b5ce6066e70/R/cohortUtilities.R#L363-L371

**Comment by catalamarti** [comment]
hi @JTBrash  thanks for reporting, a new version of DUS has been submitted to cran solving this issue (0.3.2). It has been accepted already but it will take ~24h to be available in all servers
@ilovemane can you update renv file?
